# Generated by Django 3.2.8 on 2021-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
