# Generated by Django 3.2.8 on 2021-11-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tutorial_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iconos',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tutorials',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
